spring:
  application:
    name: OrderManagmentTemporal
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: temporal
    password: temporal
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: temporal-order-group
      auto-offset-reset: earliest
  temporal:
    connection:
      target: 127.0.0.1:7233
    workers-auto-discovery:
      packages:
        - com.example.ordermanagmenttemporal
